

#define SPADE_BIT 16 //10000
#define HEART_BIT 32 //100000
#define CLUB_BIT 64 //1000000
#define DIAMOND_BIT 128 //10000000

#define SUIT ([SPADE_BIT,HEART_BIT,CLUB_BIT,DIAMOND_BIT])
#define VALUE_BITS 15

typedef struct hand_t {
	int cards;
	int num_cards;
} Hand, *PHand;

typedef enum {
	SINGLE,
	PAIR,
	TRIPLE,
	BOMB,
	TRIPLE_PLUS_SINGLE,
	TRIPLE_PLUS_PAIR,
	ROCKET,
	SINGLE_SEQUENCE,
	PAIR_SEQUENCE,
	TRIPLE_SEQUENCE,
	TRIPLE_SEQUENCE_PLUS_SINGLE,
	TRIPLE_SEQUENCE_PLUS_PAIR,
} HandType;