#!/bin/sh

echo "Is it moring? Please answer yes or no"
read timeofday

case "$timeofday" in
	yes ) echo "Good Morning";;
	no  ) echo "Good Afternoon";;
	y   ) echo "Good Morning";;
	n   ) echo "Good Afternoon";;
	*   ) echo "Sorry ,Answer not recognized";;
esac

exit 0
