#define CLIP_MATRIX 0
#define CLIP_MATRIX_1 1
#define CLIP_MATRIX_2 2
#define CLIP_MATRIX_3 3

#define WORLD_MATRIX 4
#define WORLD_MATRIX_1 5
#define WORLD_MATRIX_2 6
#define WORLD_MATRIX_3 7

#define INVERSE_WORLD_MATRIX 8
#define INVERSE_WORLD_MATRIX_1 9
#define INVERSE_WORLD_MATRIX_2 10

#define LIGHT_POSITION 11
#define EYE_VECTOR 12
#define SPEC_POWER 13
#define SPEC_COLOR 14
#define DIFFUSE_COLOR 15
#define LIGHT_ATTENUATION 17
